default_install_hook_types:
    - pre-commit
    - prepare-commit-msg
default_stages:
    - pre-commit
repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: detect-aws-credentials
      args: [ '--allow-missing-credentials' ]
    - id: detect-private-key
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-added-large-files
      stages: [pre-commit]

- repo: https://github.com/gitleaks/gitleaks
  rev: v8.18.4
  hooks:
    - id: gitleaks

- repo: https://github.com/tofuutils/pre-commit-opentofu
  rev: v2.1.0
  hooks:
  - id: tofu_tflint
    args:
      - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
  - id: tofu_docs
    args:
      - --hook-config=--create-file-if-not-exist=true
    exclude: (\.terraform.*|modules/.*|vars/.*)$
